// Extracts Inter Bold E and e glyph paths via opentype.js and writes
// pages/22/inter-glyphs.ts. Run: `pnpm node-ts scripts/extract-glyphs.ts`.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import opentype from 'opentype.js'

const here = dirname(fileURLToPath(import.meta.url))
const fontPath = resolve(here, '../node_modules/@fontsource/inter/files/inter-latin-700-normal.woff')

const buf = readFileSync(fontPath)
const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer
const font = opentype.parse(ab)

const FONT_SIZE = 100

function extract(char: string) {
  const path = font.getPath(char, 0, 0, FONT_SIZE)
  return {
    d: path.toPathData(2),
    box: path.getBoundingBox(),
  }
}

const E = extract('E')
const e = extract('e')

// Split the e glyph at each uppercase M command into subpaths
// (lowercase e has an outer shape + inner hole — two subpaths).
function splitSubpaths(d: string): string[] {
  const matches = [...d.matchAll(/M/g)].map((m) => m.index!)
  return matches.map((start, i) => d.slice(start, matches[i + 1] ?? d.length))
}

const eSubpaths = splitSubpaths(e.d)

const out = `// AUTO-GENERATED by scripts/extract-glyphs.ts — do not edit by hand.
// Inter Bold (700), font-size ${FONT_SIZE}. SVG y axis (baseline at y=0,
// ascenders negative y, descenders positive y).
export const E_PATH = ${JSON.stringify(E.d)}
export const E_LOWER_PATH = ${JSON.stringify(e.d)}
export const E_LOWER_SUBPATHS = ${JSON.stringify(eSubpaths)}
export const E_BOX = ${JSON.stringify(E.box)}
export const E_LOWER_BOX = ${JSON.stringify(e.box)}
`

const outPath = resolve(here, '../pages/22/inter-glyphs.ts')
writeFileSync(outPath, out)
console.log('Wrote', outPath)
console.log('E box:', E.box)
console.log('e box:', e.box)
