// Extracts Inter Bold E and e glyph paths via opentype.js and writes
// pages/22/inter-glyphs.ts. Run: `pnpm node-ts scripts/extract-glyphs.ts`.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, resolve } from 'node:path'
import opentype from 'opentype.js'

const here = dirname(fileURLToPath(import.meta.url))
const fontPath = resolve(here, '../node_modules/@fontsource/inter/files/inter-latin-700-normal.woff')

const buf = readFileSync(fontPath)
const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength) as ArrayBuffer
const font = opentype.parse(ab)

const FONT_SIZE = 100

type Cmd = {
  type: string
  x?: number
  y?: number
  x1?: number
  y1?: number
  x2?: number
  y2?: number
}

function extract(char: string) {
  const path = font.getPath(char, 0, 0, FONT_SIZE)
  return {
    d: path.toPathData(2),
    box: path.getBoundingBox(),
    commands: path.commands as Cmd[],
  }
}

function splitSubpaths(commands: Cmd[]): Cmd[][] {
  const out: Cmd[][] = []
  let cur: Cmd[] = []
  for (const c of commands) {
    if (c.type === 'M' && cur.length > 0) {
      out.push(cur)
      cur = []
    }
    cur.push(c)
  }
  if (cur.length) out.push(cur)
  return out
}

function centroid(commands: Cmd[]): { cx: number; cy: number } {
  let sx = 0
  let sy = 0
  let n = 0
  for (const c of commands) {
    if (c.x !== undefined && c.y !== undefined) {
      sx += c.x
      sy += c.y
      n++
    }
  }
  return { cx: sx / n, cy: sy / n }
}

function scaleAround(commands: Cmd[], cx: number, cy: number, s: number): Cmd[] {
  const tx = (x: number) => cx + (x - cx) * s
  const ty = (y: number) => cy + (y - cy) * s
  return commands.map((c) => {
    const n: Cmd = { type: c.type }
    if (c.x !== undefined && c.y !== undefined) {
      n.x = tx(c.x)
      n.y = ty(c.y)
    }
    if (c.x1 !== undefined && c.y1 !== undefined) {
      n.x1 = tx(c.x1)
      n.y1 = ty(c.y1)
    }
    if (c.x2 !== undefined && c.y2 !== undefined) {
      n.x2 = tx(c.x2)
      n.y2 = ty(c.y2)
    }
    return n
  })
}

function commandsToD(commands: Cmd[]): string {
  const f = (v: number) => v.toFixed(2)
  return commands
    .map((c) => {
      switch (c.type) {
        case 'M':
          return `M${f(c.x!)},${f(c.y!)}`
        case 'L':
          return `L${f(c.x!)},${f(c.y!)}`
        case 'Q':
          return `Q${f(c.x1!)},${f(c.y1!)} ${f(c.x!)},${f(c.y!)}`
        case 'C':
          return `C${f(c.x1!)},${f(c.y1!)} ${f(c.x2!)},${f(c.y2!)} ${f(c.x!)},${f(c.y!)}`
        case 'Z':
          return 'Z'
        default:
          return ''
      }
    })
    .join('')
}

const E = extract('E')
const e = extract('e')

const eSubpaths = splitSubpaths(e.commands)
if (eSubpaths.length !== 2) {
  throw new Error(`Expected 2 subpaths for 'e', got ${eSubpaths.length}`)
}
const eOuterCmds = eSubpaths[0]
const eHoleCmds = eSubpaths[1]
const { cx: holeCx, cy: holeCy } = centroid(eHoleCmds)
// Collapse the hole to its centroid for the "source" path: at t=0 the hole
// has zero area and is invisible inside the filled E; at t=1 it's the
// full e hole. Topology is preserved so Flubber's interpolate produces a
// clean radial expansion.
const eHoleTinyCmds = scaleAround(eHoleCmds, holeCx, holeCy, 0.01)

const out = `// AUTO-GENERATED by scripts/extract-glyphs.ts — do not edit by hand.
// Inter Bold (700), font-size ${FONT_SIZE}. SVG y axis (baseline at y=0,
// ascenders negative y, descenders positive y).
export const E_PATH = ${JSON.stringify(E.d)}
export const E_LOWER_PATH = ${JSON.stringify(e.d)}
export const E_LOWER_OUTER = ${JSON.stringify(commandsToD(eOuterCmds))}
export const E_LOWER_HOLE = ${JSON.stringify(commandsToD(eHoleCmds))}
export const E_LOWER_HOLE_TINY = ${JSON.stringify(commandsToD(eHoleTinyCmds))}
export const E_BOX = ${JSON.stringify(E.box)}
export const E_LOWER_BOX = ${JSON.stringify(e.box)}
`

const outPath = resolve(here, '../pages/22/inter-glyphs.ts')
writeFileSync(outPath, out)
console.log('Wrote', outPath)
console.log('E box:', E.box)
console.log('e box:', e.box)
console.log('hole centroid:', { holeCx, holeCy })
